CMakeLists.txt
I'm building a snap for our production deployment and the release target does not include pyth_tx
=> Add pyth_tx to the release target

pc/manager.cpp, pc/request.cpp, pcapps/pyth.cpp
Closes #13 
Closes #11 
```
pyth: Add hidden -d debug logging flag to help text. 
```
```
manager: Set error state if program key is not found.
Previously, the code would crash here.
```
```
pyth: Print error and return 1 on mapping key failure.
Previously, pyth would return a 0 exit code but not return any data.
This could happen if the mapping key is missing or invalid.
Also, only try updating the price::pub_idx_ if the manager actually
has a publish public key. This was causing a crash when running the
tools without a publish keypair. This should be valid for running
in monitoring / consuming modes.
```
```
pyth: Add get_all_products command. 
```
=> [pyth] Add "get_all_products" command and fix various crashes.

pcapps/pyth.cpp
This change allows writing `./pyth upd_price_val` which takes an explicit price, confidence interval and status value for publishing.
=> pyth.cpp: upd_price takes price value, confidence and symbol status

pc/net_socket.cpp, pc/net_socket.hpp, pc/rpc_client.cpp, pc/rpc_client.hpp
filtering by account type avoids sending the larger accounts assigned to the program that don't update often (or at all)
it was tested with this code:
`areq_->set_account_type( PC_ACCTYPE_PRICE );`
which will be included in a later pull request
this reduced bandwidth usage by 50% for this RPC call
=> add filtering based on account type to getProgramAccounts

doc/https-for-rpc-providers.md, doc/nginx-configs/bison-trails-virt-server-config.conf
This adds a nginx config to reverse proxy [Bison Trails](https://bisontrails.co/)
Tested locally:
```
$ websocat -v ws://localhost:7803
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
{"jsonrpc": "2.0", "id": 1, "method": "logsSubscribe", "params": [ {"mentions": ["11111111111111111111111111111111"]}, { "commitment": "finalized"}]}
{"jsonrpc":"2.0","result":4,"id":1}
^C
$ websocat -v ws://localhost:7903
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws …
```
=> Add bison trails nginx config

doc/nginx-configs/blockdaemon-virt-server-config.conf, doc/nginx-configs/figment-virt-server-config.conf, doc/nginx-configs/triton-one-virt-server-config.conf
Using variables for the hosts in the example configs lets nginx resolve them lazily. This allows editing only the specific config you want to test and nginx will still start to test things out.
Otherwise, nginx fails to start when one of the `proxy_pass` hosts failed to lookup `YOUR_SERVER...`. It looks like this:
2021/09/16 11:52:29 [emerg] 126854#0: host not found in upstream "YOUR_SERVER-solana-01.bdnodes.net" in blockdaemon-virt-server-config.conf:64
Note: The triton one config was only tested with ip whitelisting as I didn't have access to a triton cluster with authentication enabled.
Block Daemon
----------------
```
$ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}' http://localhost:7900
{"jsonrpc":"2.0","result":"ok","id":1}
$ …
```
=> Nginx proxy config cleanup

pc/manager.hpp, pc/request.cpp, pc/request.hpp, pcapps/admin_request.hpp
- Make hidden overloaded virtual functions explicit, with private 'using base::method'.
- Change 'virtual' to 'override' in overridden methods.
- Remove unused private member variables.
=> Fix clang build failures under -Werror:

program/src/oracle/pd.h
- Allows including `pd.h` in test sources without adding `-Wno-unused-function`.
- See https://github.com/pyth-network/pyth-client/pull/91
=> `pd.h`: Change `static` to `static inline`.

.github/workflows/docker.yaml, docker/Dockerfile, scripts/build-bpf.sh, scripts/build.sh
- make `-z defs` work with bpf sources calling `sol_invoke`
- add `build-bpf.sh`, intended to be shared by `serum-pyth`
- remove `GITHUB_WORKSPACE` reference from `Dockerfile`
- old behavior was expanding to an empty string
- instead set build context to `GITHUB_WORKSPACE` in `docker.yaml`
- make `SOLANA_VERSION` available for `docker run`/`docker inspect`
- comments, whitespace, github workflow step names
=> `Dockerfile` improvements

scripts/build.sh
This scripts should generally be used from within the Docker env, but it's sometimes useful to run it from the host for local testing. This change avoids requiring `brew install coreutils` on OS X.
=> build.sh: remove usage of `realpath` (requires coreutils on OS X)

.idea/cmake.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/scopes/markdown.xml, CMakeLists.txt
- Add pseudo-bpf cmake target conditionalized on `-DSolana`, passed via CLion but not build scripts.
- Enable static analysis on `program/` sources and resolving solana & criterion headers.
- Restrict spelling and grammar checks to markdown files.
=> Changes for CLion:

doc/example-nginx-triton1.conf
With http/1.0 negotiation for websockets, the websocket negotiation will fail.
This is per the HTTP spec:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism
=> Use http/1.1 for both websockets and regular rpc

doc/example-nginx-bisontrails.conf, doc/example-nginx-blockdaemon.conf, doc/example-nginx-figment.conf
"""
Use http/1.1 for both websockets and regular rpc (#137)
With http/1.0 negotiation for websockets, the websocket negotiation will fail.
"""
=> use http/1.1 for websockets

pc/request.cpp, pc/request.hpp
These accessors make it easy for people to avoid using the symbol
=> Accessors for base/quote currencies

docker/Dockerfile, pc/manager.cpp, pc/request.cpp, pc/user.cpp, pc/user.hpp, pyth/tests/conftest.py, pyth/tests/test_update_price.py
This PR changes the semantics of the `update_price` pythd JRPC call. Previously, updates were immediately sent to Solana (or `pyth_tx`) using a new transaction for each update. Instead, we buffer all received updates inside pythd, and send all buffered updates in bulk whenever a new slot is available. This uses less transactions at a cost of slightly increased latency.
I have tried to follow existing code styles and conventions as much as possible.
A follow-up PR will modify the on-chain program, adding a batch update endpoint which will only fail the transaction if all the individual price updates in that batch fail. This will ensure publishing failures on one product won't block updates for unaffected products.
=> Batch updates in update_price JRPC call

pc/rpc_client.cpp, pc/rpc_client.hpp, program/src/oracle/oracle.c, program/src/oracle/oracle.h, program/src/oracle/test_oracle.c, pyth/tests/conftest.py, pyth/tests/test_update_price.py
This PR adds a new instruction to the Oracle: `cmd_upd_price_no_fail_on_error`. This is exactly the same as `cmd_upd_price`, but never fails the instruction, and therefore the transaction, even if the update is unsuccessful. This is because we will soon send update instructions in batches, and want to prevent a failure in one price feed blocking updates of other prices.
- Add the `cmd_upd_price_no_fail_on_error` instruction.
- Change `pythd` to send `cmd_upd_price_no_fail_on_error` JPRC requests instead of `cmd_upd_price`.
- `pythd` changes: the existing `pythd` integration tests for the JRPC `update_price` request will now cover the new `e_cmd_upd_price_no_fail_on_error` code paths.
- Oracle changes: new Oracle tests for the `cmd_upd_price_no_fail_on_error` instructions have been added, …
=> Add batch price update instruction to Oracle

program/src/oracle/test_oracle.c, program/src/oracle/upd_aggregate.h, pyth/tests/qset/36.result, pyth/tests/qset/39.result
This removes the old aggregation logic and simply stores the price and confidence directly in the aggregate. This follows up on the aggregation logic in v2 extracted from #139 and removes the grafting on input to the TWAP calculation.
=> Remove old aggregation logic.

program/src/oracle/oracle.h
Move `e_cmd_upd_price_no_fail_on_error`, to ensure backwards-compatibility.
=> Re-order e_cmd_upd_price_no_fail_on_error enum

doc/cpp-batching-upgrade.md, pctest/test_publish.cpp
This PR adds some documentation explaining how publishers which link to the C++ bindings need to modify their code in order to send batch price updates. The `test_publish.cpp` example has also been updated to demonstrate this.
=> Add documentation and update example for batch price updates

doc/getting_started.md
New publishers should use the websocket API.
=> Remove references to the C++ bindings from the Getting Started doc

pctest/fuzz.cpp, pctest/test_qset.cpp, pctest/test_twap.cpp, program/src/oracle/oracle.c, program/src/oracle/oracle.h, program/src/oracle/test_oracle.c, program/src/oracle/upd_aggregate.h
This PR changes the semantics of the `pc_price.prev_slot_`, `pc_price.prev_price_` and `pc_price.prev_conf_` fields to only store the value of the previous price aggregate if the previous price aggregate had a status of TRADING. We also store a new piece of data, the Solana unix timestamp of this previous aggregate, for convenience.
=> Store value of previous price aggregate if the status is trading

program/src/oracle/oracle.c
In case the account is being reinitialized, the prev_timestamp should be reset.
=> Reset previous timestamp when account is reinitialized

program/src/oracle/oracle.c, program/src/oracle/test_oracle.c
This should never be greater than the number of total price components.
=> Add bounds check to upd_test num_ parameter

program/src/oracle/oracle.c, program/src/oracle/test_oracle.c
This PR checks that the data held by each account is exactly the size we expect, and that the accounts hold enough lamports to be rent exempt.
=> Check that accounts are rent exempt

CMakeLists.txt
When compiling against OpenSSL versions => 3.0, the build will error out
due to the usage of methods like SHA256_Update, SHA256_Init, etc..
See: https://wiki.openssl.org/index.php/OpenSSL_3.0
While these functions should probably be ported to their new
equivalents, this at least allows for the client to be compiled.
=> Add Compiler flag to ignore deprecated OpenSSL declarations

pc/request.cpp
The counter tracking the start element of each batch inside `pc::price::send` does not take into account the fact that the counter tracking the end of each batch is inclusive.
This results in the `inc_sent` method being called twice for the last element of each batch, resulting in an artifically low hit rate metric for those elements.
=> Fix inaccurate num_sent metric for last element in batch

program/src/oracle/oracle.c
This ensures that the rent exemption check is correct for accounts that are larger than expected, and maintains the invariant that all our accounts are one of the expected sizes.
=> Improve accuracy of rent exemption check

.github/workflows/docker.yaml
This allows us to publish images for pythd releases independently of the oracle releases.
=> Publish pythd releases

pc/manager.cpp, pc/manager.hpp, pc/user.cpp, pc/user.hpp
Expand batching to apply to all JRPC clients. This allows publishers to push prices from different systems and still benefit from the massive gas savings batching can provide.
~`price::send()` never returns false, so the logic to track which users participated in a batch could be removed without much impact.~
=> Batch price updates across all websocket users

CMakeLists.txt, docker/Dockerfile, pctest/test_publish_websocket.cpp
This PR demonstrates how to use C++ to publish price updates to the Pyth Network through the pythd websocket API described at https://docs.pyth.network/publish-data/pyth-client-websocket-api
It's a very rough, minimal example which demonstrates how to use the API.
=> Add C++ pythd websocket example

program/rust/src/lib.rs, scripts/build-bpf.sh
Running `Cargo test` compiles the oracle into native (none-bpf) code, which causes a linker error when linking with the bpf C oracle.
This PR makes it so that we do not link on cargo test. I believe this is reasonable because unit tests should not involve FFI calls. It makes more sense to unit test each component in the language it is written in. If we think we want the linking to happen, then we would need to understand how to compile the c oracle into a native architecture as well, and link to that when we run cargo test. That seems like  unnecessary work to me (specially with the issues around solana and libc compatibility), but happy to do it if we believe it's useful.
=> link with c only when target is bpf

program/c/src/oracle/oracle.c, program/c/src/oracle/test_oracle.c, program/c/src/oracle/upd_aggregate.h
In an earlier PR we made upd_price in C return SUCCESSFULLY_UPDATED_AGGREGATE when upd_aggregate is called. It turns out, update_aggregate sometimes returns early, this PR  makes upd_aggregate return a bool depending on whether the aggregate was updated
=> Only return SUCCESSFULLY_UPDATED_AGGREGATE if upd_twap was called [bug fix]

program/rust/src/bindings.h, program/rust/src/price_t_offsets.h
Deserializing the entirety of price_t in rust is inefficient when we only need a few members (atleast until we migrate price update logic to rust), and it might cause issues with Solana's limited stack.
In this PR, I add the offsets of the relevant members of price_t to the bindings generated by bindgen. This is done in a way that is robust to changes in the layout of price_t. I am debating whether it is cleaner to write a macro that generates offsets for all members, but I am feeling like this is cleaner for the time being since we only need these few members.
=> Made Price_t member offsets available to Rust

pc/request.cpp, program/c/src/oracle/oracle.c, program/c/src/oracle/oracle.h
We plan on resizing price accounts to fit the Time Machine. This PRs ensures that this does not cause existing C code to fail.
There are two places where the size of price_t not being the same as the account size can cause failures:
1-rent exempt check while validating accounts (oracle.c) 
2-Decompressing the result of the RPC request to Solana requesting to read price contracts (pythd, request.cpp)
(We do not change the default new account size for Pyth-manager because it is helpful to have accounts from the old size in unit tests, and C pyth-manager is no longer used anyway)
=> Make c robust to price account size

program/c/src/oracle/oracle.h, program/rust/build.rs, program/rust/build_utils.rs, program/rust/src/error.rs, program/rust/src/lib.rs, program/rust/src/log.rs, program/rust/src/processor.rs, program/rust/src/rust_oracle.rs, program/rust/src/time_machine_types.rs
Our design involves rersizing price accounts, as well as intercepting calls to instructions that update_the price in order to do the SMA tracking. 
In this PR:
1. We intercept the add_price calls (but we do not change their behavior yet)
2. We add a no-op update_account_version instruction that is meant to update the version number of a given account, and resize price accounts.
The purpose of this is to get feedback on the structure of the program.
It also addressed two other issues:
1. added panic and heap definitions. (These are usually added in the entrpoint! macro is solana sdk, code won't compile without them once we start using anything that code panic like arrays, etc) 
2. Updated the error message in the size of time machine assert so that it prints the correct size for better …
=> Intercepting price updates

.github/workflows/docker.yaml
Releases will now release the compiled oracle program. This will make it easier to know which version is onchain by byte comparison. It should make the process of deploying less error prone.
=> Publish binary at release

program/rust/src/deserialize.rs, program/rust/src/processor.rs
More graceful error handling in load. Now it shouldn't panic if length is not right.
=> Check length

program/rust/src/error.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/test_add_price.rs, program/rust/src/tests/test_add_product.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/tests/test_upd_product.rs
It's a little hard to debug when all account checks return InvalidArgument, so I specified the error dpending on which check failed
=> Specifying account check errors

pc/manager.cpp, pc/request.cpp, pc/request.hpp
To avoid flooding the RPC client's request queue, we only send one price update per price, per slot.
=> Only send one price update per price per slot

pc/manager.cpp, pcapps/pythd.cpp
This allows publishers to configure `pub_int`, which controls the rate at which `notify_price_sched` messages are sent.
=> Make pub_int configurable from pythd

program/rust/src/deserialize.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/test_add_mapping.rs, program/rust/src/tests/test_add_price.rs, program/rust/src/tests/test_add_product.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_del_publisher.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/tests/test_init_price.rs, program/rust/src/tests/test_set_min_pub.rs, program/rust/src/tests/test_upd_product.rs, program/rust/src/utils.rs
There were lots of helper function in rust_oracle. I moved them to deserialize, and utils. I think that the sooner we do this the better, as you can see doing it now caused a lot of files to change.
There was also a method that had the same name as a solana sdk method, so I renamed to another name (in a separate commit )
=> Move to utils

program/c/makefile, program/c/src/oracle/for_cargo_test/cpyth_test.c, program/c/src/oracle/oracle.c, scripts/build-bpf.sh
For one of the latest steps of the migration we're going to restrict the C code to the aggregation logic.
This requires exporting the function `upd_aggregate` from C to Rust. We're doing similar logic to exporting the c_entrypoint from `oracle.c`.
A subtle difficulty is that `cargo test` runs in the system architecture, so we need to compile `upd_aggregate` to this target as well. That's the goal of `for_cargo_test/cpyth_test.c`. This will allow using `upd_aggregate` in the tests.
Of course there's danger that our rust tests pass but our production code fails because they're compiling to different targets but this problem already existed with `test_oracle.c` which is also getting compiled to the system's target. Integration tests (currently pytest) should pick this up.
=> Export upd_aggregate

docker/Dockerfile, program/c/src/oracle/model/run_tests, program/c/src/oracle/sort/run_tests, program/c/src/oracle/util/run_tests, scripts/run-aggregation-tests.sh
I unearthed some tests for the aggregation logic components. They take <2min so I thought we can add them to CI. 
These tests originally imported modules that don't exist in our current setup, so I deleted those lines.
=> Run aggregation tests in CI

program/c/src/oracle/native/upd_aggregate.c, program/c/src/oracle/oracle.h, program/rust/build.rs, program/rust/src/bindings.h
the cargo build (and `./scripts/build-bpf.sh`) used were failing because we were defining these integer types multiple times. It turns out that we already have a solution to this problem in `compat_stdint.h` which  selects between the system stdint.h and the definitions in the solana sdk. 
Note that the repo still expects to be placed adjacent to a `solana` directory. I'll fix that next.
=> Make it build on macs

doc/example-nginx-triton1.conf
To connect nginx to Pythnet, a completely orthogonal, seperate configuration should be used. This should use seperate `server` and `upstream` stanzas.
=> Add example triton1 pythnet nginx configuration

program/c/src/oracle/oracle.h, program/rust/src/processor.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/mod.rs, program/rust/src/tests/pyth_simulator.rs, program/rust/src/tests/test_del_product.rs, program/rust/src/utils.rs
This is again needed to clean up the pythtest situation, where we created extra product/price accounts.
=> Command to delete a product

program/rust/src/c_oracle_header.rs, program/rust/src/deserialize.rs, program/rust/src/instruction.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/pyth_simulator.rs, program/rust/src/tests/test_add_mapping.rs, program/rust/src/tests/test_add_price.rs, program/rust/src/tests/test_add_product.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_del_price.rs, program/rust/src/tests/test_del_product.rs, program/rust/src/tests/test_del_publisher.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/tests/test_init_price.rs, program/rust/src/tests/test_set_min_pub.rs, program/rust/src/tests/test_sizes.rs, program/rust/src/tests/test_upd_aggregate.rs, program/rust/src/tests/test_upd_price.rs, program/rust/src/tests/test_upd_price_no_fail_on_error.rs, program/rust/src/tests/test_upd_product.rs, program/rust/src/time_machine_types.rs, program/rust/src/utils.rs
This PR :
- Creates rust structs in `c_oracle_header.rs` and replaces all the bindgen structs by the new structs.
=>  Create rust structs and replace bindgen structs

program/rust/src/rust_oracle.rs, program/rust/src/time_machine_types.rs
This PR:
- Cleans up the comments in `resize_price_account`
- Adds an extra rent exemption check to make sure the lamport transfer worked (paranoid check)
- Removes print statements.
=> Cleanup resize, remove print staments, add extra check

program/rust/src/tests/mod.rs, program/rust/src/tests/pyth_simulator.rs, program/rust/src/tests/test_resize_account.rs
Add a new test for the resize instruction. This instruction will enable price account resizing for adding more publishers and the settlement prices.
=> Add test for resize instruction

program/rust/src/deserialize.rs, program/rust/src/error.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/test_add_product.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/utils.rs
- Move the `minimum_size`  check to `load_checked` and `initialize_checked` from `check_valid_signable_account` and `check_valid_writable_account`. This allows to leverage the PythAccount trait for the check. It makes sense to have that check in the deserialization functions because if the account is too small deserialization will fail.
- Move `check_valid_fresh_account` to `initialize_pyth_account_checked`. These two functions are always called together. Makes it harder to accidentally reinitialize an account.
=> Move minimum size check to load_checked and initialize_checked

program/c/src/oracle/oracle.h, program/rust/src/c_oracle_header.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/test_init_price.rs, program/rust/src/utils.rs
I want to move these constants to Rust.
They can be deleted from `oracle.h`. Additionally, we no longer have to use `as` conversions when they're used.
=> Port MAX_CI_DIVISOR and MAX_NUM_DECIMALS

program/rust/src/rust_oracle.rs
Cleanup of some unsafe conversions in the oracle code.
=> Remove as conversions from rust_oracle.rs

program/rust/src/c_oracle_header.rs, program/rust/src/deserialize.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_utils.rs
I realized minimum_size can be a constant. This will allow to cleanup some other parts.
=> Turn minimum function into constant

pc/user.cpp
To ensure clients are able to subscribe to `price_sched` updates when only one network is connected at startup, `subscribe_price_sched` should check to see if the account is present in either network.
=> Check to see if price account exists in either network when handling subscribe_price_sched

program/rust/src/deserialize.rs, program/rust/src/error.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/test_add_mapping.rs, program/rust/src/tests/test_add_price.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/tests/test_init_price.rs
Replace `InvalidArgument` by `InvalidNumberOfAccounts` and `InvalidAccountHeader`.
=> Improve errors

program/rust/src/rust_oracle.rs, program/rust/src/time_machine_types.rs
I'm refactoring the gating of the sma feature. To make sure we never go into this part of the code in production.
`resize_price_account` is still available but:
1. Requires a price account signature
2. If an account is resized our code keeps working, because our code only checks that `account.data.len() >= MINIMUM_SIZE`
=> Gate sma with test flag

program/c/makefile
My code wasn't compiling on the RHEL vm. The compiler asked me to add this flag.
It only affects the tests, because cpyth-native.o is only used to test locally.
After reading online what the flag does, and seeing it's present in the `bpf.mk` makefile, I don't see the harm in adding it.
=> Add fPIC flag 

pc/rpc_client.cpp, program/c/src/oracle/oracle.h
Solana is going to start using the compute limit to pack transactions into blocks and to calculate gas fees.
=> [wip] Request compute units for price update transactions

pc/rpc_client.cpp, program/c/src/oracle/oracle.h
Setting this so that we are able to pay more for compute units, and hopefully increase our transaction success rate.
=> Set price per compute unit

program/rust/src/c_oracle_header.rs, program/rust/src/tests/test_upd_price.rs, program/rust/src/tests/test_upd_price_no_fail_on_error.rs, program/rust/src/tests/test_upd_sma.rs, pyth/tests/test_update_price.py
This is getting the hotfix into the main branch.
https://github.com/pyth-network/pyth-client/compare/ci_hotfix?expand=1
=> Set CI threshold to 3

Cargo.toml, program/rust/src/processor.rs, program/rust/src/rust_oracle.rs, program/rust/src/time_machine_types.rs
This PR tweaks some compilation settings and removes some unused code, to reduce the size of the Oracle binary to 68576B.
=> Reduce size of Oracle binary

pc/manager.cpp, pc/manager.hpp, pc/request.cpp, pc/rpc_client.cpp, pc/rpc_client.hpp, pcapps/pythd.cpp
This allows publishers to configure the amount and cost of CU units used in `upd_price` transactions. By default we specify the amount, but not the cost.
Note that one code path, that used by the `pyth upd_price_val` cli command, used only in tests, uses a slightly different method of sending the transaction than the websocket `update_price` command. To ensure this still works, we preserve the signatures of the existing `pc::rpc::upd_price::build` and `pc::rpc::upd_price::request` methods, instead adding additional versions of these that allow specifying the additional parameters.
=> Make requested CU amount and price in upd_price transactions configurable in pythd

pc/request.cpp
We add an entry to the list of unacked transactions for each price account in a batch. This means that there are more "unacked transactions" tracked then really exist, which results in an unnecessarily high amount of `too many unacked price update transactions` messages being printed. This PR therefore only stores one update per batch.
=> Fix spurious too many unacked price update transactions message

program/rust/Cargo.toml, program/rust/src/processor/upd_permissions.rs, program/rust/src/utils.rs
Remove bincode.  We are forced to use bytemuck to deserialize the programdata account.
This a big size gain : 170k -> 99k
=> Remove bincode

program/rust/src/accounts.rs, program/rust/src/tests/test_upd_permissions.rs, program/rust/src/utils.rs
97k -> 92k
More details on ptal.
=> Make PDA init simpler

docker/Dockerfile, scripts/get-bpf-tools.sh
With the current solana-labs bpf-tools (the toolchain that builds bpf programs), the flags `-Z build-std=std,panic_abort` don't work. These flags compile the standard rust library from scratch and make the program smaller. 
There is evidence that the solana team plans to release a version that support this : https://github.com/solana-labs/solana/blob/9f370475d40dbe68f1a51d34fc3df07e5327d6c3/sdk/cargo-build-sbf/src/main.rs#L625
This PR is meant to make the repo use a fork of bpf-tools instead of the solana-labs release. The only difference between the my fork and solana-labs is that my fork uses https://github.com/solana-labs/compiler-builtins/tree/sbf-tools-v1.30 instead of  https://github.com/solana-labs/compiler-builtins/tree/bpf-tools-v1.27 (a package bump basically) . 
TLDR : I think …
=> Use custom bpf-tools

README.md, docker/Dockerfile, pctest/setup_local.sh, pctest/setup_pub.sh, program/c/makefile, program/rust/build.rs, scripts/build-bpf.sh, scripts/patch-solana.sh
The goal of this PR is fixing an annoying quirk of the repo that meant you had to the `pyth_client` repo and the `solana` repo side to side in the same folder. The trick is we can find the solana local installation by doing `which cargo-build-bpf`. This is inspired by https://github.com/guibescos/example-helloworld .
Resolving the solana installation ended up a little bit dirty in `build.rs` because bindgen needs to find the solana C headers. This will get better when we get rid of the C headers.
=> Fix solana dir

docker/Dockerfile, scripts/build-bpf.sh, scripts/check-size.sh
The goal of this PR : 
- Add the flags `-Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort` to the compilation of the oracle. This flags compile the rust std library instead of using a rebuilt binary and disable panic tracebacks.
- Add a script that checks the size of the program for CI against the hardcoded size of the onchain account.
Once this PR gets merged, it'll fit onchain!
=> Add compilation flags and check size in CI

program/rust/src/c_oracle_header.rs, program/rust/src/processor/add_price.rs, program/rust/src/tests/test_add_price.rs
A lot of price feeds have been created in the past with min_pub equal to 0, leading to protocols thinking the price is live when it's not.
The goal is changing the default behavior so it's less error prone. By default price accounts will have min_pub equal to 20.
=> Default value of 20 for min pub

program/c/src/oracle/oracle.h, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_upd_price.rs, program/rust/src/tests/test_upd_sma.rs
We currently can't tell the difference between data providers who intentionally publish status=UNKNOWN and data providers that are being automatically filtered out of the aggregate. This is causing problems in the conformance script, where incorrect prices are showing up as the data provider being offline.
This change adds an IGNORED status to represent the case where the data provider is intentionally kicked out.
=> Add new status flag for data providers kicked out of aggregate

rust-toolchain
CI started failing (the bpf tests), I realized a new version of rust got released and was making the tests crash, so I'm pinning the version of rust to one where things worked.
=> Add toolchain

.github/workflows/docker.yaml, SECURITY.md
Changing our releases to :
- oracle-vx.x.x
=> Switch to oracle releases

README.md, program/c/src/oracle/upd_aggregate.h, program/rust/src/lib.rs, program/rust/src/tests/test_ema.rs, program/rust/src/tests/test_upd_price.rs, program/rust/test_data/aggregation/2.result, program/rust/test_data/aggregation/3.result, program/rust/test_data/aggregation/31.result, program/rust/test_data/aggregation/32.result
We want negative prices for yields. The only blocker for negative numbers is an overly-aggressive `if` statement in the aggregation logic designed to prevent overflows. I updated this if statement to the minimum necessary conditions to prevent overflow.
Note that the aggregation algorithm (`price_model`) is already tested with negative numbers (see test_price_model.c) so this should be fine. I also added a test to make sure negative numbers get aggregated properly, and changed some of the existing test cases that include negative numbers.
There was also a temporary check in the ema calculation that prevented negative numbers. I removed that check and added reasonably extensive tests for negative emas to validate the fix.
=> Allow negative prices in aggregation

program/c/makefile
I went to the dark corner of the internet to fix this : https://macports-users.macosforge.narkive.com/Wa9Zfepg/why-ar-doesn-t-call-ranlib-on-mac
Tried one of the tips and it seems to work.
=> Fix unresolved_symbol error on Mac

program/rust/src/accounts.rs
I need to make to program smaller again. This is one idea.
Everytime we create a new account, we manually zero it. 
I think this is and has always been unnecessary. Being able to create non-zero accounts belonging to a given program would break solana.
=> [size-hack] Remove clear account

program/rust/src/accounts/price.rs, program/rust/src/tests/test_twap.rs, program/rust/src/tests/test_upd_price_v2.rs
The definition of the TWAP gap has been bothering me, because it doesn't let you determine how long the gap was. This means that the validity condition for a twap is going to be something like "are there zero gaps?", which is rather brittle.
This PR changes the definition of the gap to be the number of slots of downtime. This allows us to configure the validity condition to be like "downtime < 1%", which is more robust.
=> Update definition of twap gap

program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_message.rs
There's some awkwardness around whether the messages get created from PriceAccount or PriceAccoutV2 (the twap fields only exist in PriceAccountV2) but we can work on that later. Right now accounts have to be upgraded before messages start getting sent.
Key point is the `TwapMessage` struct.
=> Add TWAP Message format

program/rust/src/processor/upd_price.rs
explicitly set type of discriminator to be [u8; 8] otherwise `Instruction::new_with_borsh` assumes it's a `[i32;8]` which will cause the ix to be unrecognized when the oracle program attempts to invoke the message buffer CPI call since it will be padded with extra 0's
=> Explicitly set type of discriminator

program/rust/Cargo.toml, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/lib.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_message.rs
This PR adds deserialization to PriceFeedMessage and TwapMessage. It also introduces a Message enum which wraps messages. I have refactored the code such as renaming `as_bytes` to `to_bytes` because `as_bytes` usually returns a reference from a type that is wrapping bytes.
The purpose of this change is to use these structs from this crate (as library) in hermes.
=> Add deserialization to price messages

program/rust/src/processor/upd_price.rs
How confident are we that pyth-agent/pyth-d never publish for a future slot?
=> Reject prices in the future

Cargo.lock, program/rust/Cargo.toml, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/lib.rs
This PR extends the `Message` type with features that are helpful to users consuming the program as a library.
- Adds strum/serde to `Message*` during `--features = library` use.
- Adds methods to extract id/publish_time from any message.
- Exports the new `MessageType` enum generated by strum.
=> Improvements to Message in the Oracle Program

Cargo.lock, Cargo.toml, program/rust/Cargo.toml, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/lib.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_message.rs
Since the custom serialization implementations are solana specific and mainly for reducing the binary size, they are kept in this package via a custom trait.
Deserialization functions were removed since they were not used and the default serde provided by pythnet sdk should work identically. Serialization tests are now repurposed to test our custom serialization and the general deserialization lead to the same original structure.
=> Use message structures defined in pythnet sdk

scripts/build-bpf.sh, scripts/check-size.sh
This change makes `scripts/build-bpf.sh` provide both solana/pythnet contract flavors in a custom `target/pyth` directory. It should help disambiguate the binaries and make building for both environments a single step. Previously, the build would overwrite the Solana contract flavor with the `--features pythnet` version.
=> scripts/build-bpf.sh: Move contract binaries to target/pyth/{solana|pythnet}

.github/workflows/docker.yaml
Revert back to `oracle-v` releases
=> One release instead of two releases (one for mainnet and one for pythnet)

.pre-commit-config.yaml, pcapps/pyth_csv.cpp, program/c/makefile, program/c/src/oracle/native/upd_aggregate.c, program/c/src/oracle/oracle.h, program/c/src/oracle/upd_aggregate.c, program/c/src/oracle/upd_aggregate.h, program/rust/Cargo.toml, program/rust/build.rs, program/rust/src/accounts/price.rs, program/rust/src/processor/add_publisher.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_sizes.rs
This change extends all methods that touch the price component array to use 64 publishers on Pythnet. This includes publisher addition/deletion and, notably, aggregation logic. The latter is the reason why we don't use all 128 publisher slots on Pythnet - the compiled size of `upd_aggregate` under 128 publishing slots breached the stack size limits, resulting in various tests failing with `entered unreachable code` panics.
* `program/c/makefile` - `CFLAGS` passthrough
* `program/c/src/oracle/oracle.h` - Use a `PC_PYTHNET` feature macro to decide the value of `PC_COMP_SIZE`, disambiguate into `PC_COMP_SIZE_SOLANA` and `PC_COMP_SIZE_PYTHNET`.
* `program/rust/build.rs` - detect the `pythnet` feature and define `PC_PYTHNET`` for the make build if set.
* `program/rust/src/accounts/price.rs` - …
=> Extend `upd_aggregate` and `add/del_publisher` to support 64 price components on pythnet

program/rust/src/accounts.rs, program/rust/src/tests/test_init_mapping.rs, program/rust/src/tests/test_upd_price.rs, program/rust/src/tests/test_upd_price_v2.rs
few typo I came across while studying the code. have a nice evening.
=> chore(program/rust/src): typo fix

program/c/src/oracle/native/upd_aggregate.c
This was causing issues when building locally
=> Update features.h path

Cargo.lock, program/c/src/oracle/oracle.h, program/c/src/oracle/upd_aggregate.h, program/rust/Cargo.toml, program/rust/src/accounts/price.rs, program/rust/src/tests/test_twap.rs, program/rust/src/tests/test_upd_aggregate.rs
add configurable max latency in slots between send and receive
for price feeds with more publishers this can be reduced instead of using the default 25 value to reduce latency
=> add support to configure max latency

program/rust/src/processor/add_price.rs, program/rust/src/processor/add_product.rs, program/rust/src/processor/add_publisher.rs, program/rust/src/processor/del_price.rs, program/rust/src/processor/del_product.rs, program/rust/src/processor/del_publisher.rs, program/rust/src/processor/init_mapping.rs, program/rust/src/processor/init_price.rs, program/rust/src/processor/set_max_latency.rs, program/rust/src/processor/set_min_pub.rs, program/rust/src/processor/upd_product.rs, program/rust/src/tests/test_check_valid_signable_account_or_permissioned_funding_account.rs, program/rust/src/utils.rs
Now that the old permissions are gone, we can cleanup some code where the user could choose whether or not to pass the permissions account
=> chore: cleanup permissions

program/c/src/oracle/upd_aggregate.h, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_upd_aggregate.rs
this is the first refactor in part of the same slot agg changes, intentionally keeping it small and limited to `upd_twap` so that it's easier to review
=> refactor: move upd_twap from upd_aggregate to rust upd_price

.github/workflows/docker.yaml, .pre-commit-config.yaml, Cargo.lock, README.md, program/c/makefile, program/c/src/oracle/native/upd_aggregate.c, program/c/src/oracle/oracle.h, program/c/src/oracle/upd_aggregate.c, program/rust/Cargo.toml, program/rust/build.rs, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/mod.rs, program/rust/src/tests/pyth_simulator.rs, program/rust/src/tests/test_sizes.rs, scripts/build-bpf.sh
solana specific code is duplicated in https://github.com/pyth-network/pyth-client/tree/solana so we have a fallback in case we need to make any fix
=> refactor: remove pythnet feature flag

.gitignore, program/c/src/oracle/oracle.h, program/c/src/oracle/upd_aggregate.h, program/rust/src/accounts/price.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/mod.rs, program/rust/src/tests/test_ema.rs, program/rust/src/tests/test_full_publisher_set.rs, program/rust/src/tests/test_publish.rs, program/rust/src/tests/test_publish_batch.rs, program/rust/src/tests/test_sizes.rs, program/rust/src/tests/test_upd_aggregate.rs, program/rust/src/tests/test_upd_price_no_fail_on_error.rs, program/rust/src/tests/test_upd_price_v2.rs, program/rust/src/tests/test_utils.rs
This reverts commit 65949e0980380052daa8c80eb7988bed5640c332.
=> Revert "feat: aggregate in the same slot (#394)"

program/rust/src/accounts/price.rs, program/rust/src/processor/add_publisher.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_upd_price_v2.rs
This change brings down the average cost of a price update without aggregation from 5k to 2k by moving from unordered list of publishers to an ordered list of publishers on doing binary search on lookup. It will fall back to linear search if the binary search fails.
Also add_publisher now tries to sort the list with 000... publisher as a migration path. The sort is implemented in a way to be efficient and small (in code size). There is an insertion sort upon each new publisher to make sure the list remains sorted. del_publisher won't change the order of the list so it will remain sorted.
The heavy code path for publishers now uses `sol_memcmp` (on sorting and lookup) to be more optimized (it costs 10 CU and apparently publisher equality is a few times more expensive). I checked sol_memcmp …
=> refactor: use ordered publisher list

program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/utils.rs
- Remove rent check because it costs 500CU (+10% of upd_price without aggregate) and it really is not needed.
- Use abs() on checking confidence threshold because it's incredibly slow on negative prices (2000CU). We don't have negative prices but will guard us in the future.
=> refactor: optimize some checks on upd_price

SECURITY.md
This moves the bug bounty program from self-hosted to Immunefi hosted.
=> Update bounty to Immunefi

Cargo.lock, program/rust/Cargo.toml, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/lib.rs, program/rust/src/processor.rs, program/rust/src/processor/add_publisher.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/mod.rs, program/rust/src/tests/test_add_publisher.rs, program/rust/src/tests/test_aggregate_v2.rs, program/rust/src/tests/test_sizes.rs, program/rust/src/tests/test_twap.rs, program/rust/src/tests/test_upd_price_with_validator.rs, program/rust/src/validator.rs
- Change dependency versions to make the crate compatible with pythnet validator
- Add flags to price account to track transition from v1 to v2
- Implement transition between v1 and v2 by calling add_publisher with a special pubkey
- Skip aggregation and message buffer update in the oracle program if v2 aggregation is enabled
- Clear message buffers after transition to v2
- Expose aggregation as a library function to be used in the validator
=> Support aggregation in validator

program/c/src/oracle/oracle.h
This pull request fixes a minor typo in the `oracle.h` file. The word **"tighly"** has been corrected to **"tightly"** in a comment explaining the `ZSTD_UPPER_BOUND` constant.
This change updates a comment to provide clearer documentation. It has no impact on functionality or runtime behavior.
- `program/c/src/oracle/oracle.h`
```diff
- // It is set tighly to the current price account + 96 component prices + 48 bytes for cumulative sums
+ // It is set tightly to the current price account + 96 component prices + 48 bytes for cumulative sums
=> Fix Typo in `oracle.h` File
