js/.gitignore, js/.prettierrc, js/README.md, js/jestconfig.json, js/package-lock.json, js/package.json, js/src/__tests__/Example.test.ts, js/src/__tests__/Mapping.test.ts, js/src/__tests__/Price.test.ts, js/src/__tests__/Product.test.ts, js/src/index.ts, js/tsconfig.json, js/tslint.json
https://www.npmjs.com/package/@pythnetwork/pyth-client
=> initial js lib

README.md
I've called with the pyth team and made sure that this dependency is needed to build the program. I'm Tina from Moet finance, thanks!
=> Add zlib1g-dev in readme

docker/Dockerfile
=> grant sudo access to pyth user

doc/websocket_api.md, pc/attr_id.cpp, pc/attr_id.hpp, pc/request.cpp, pc/request.hpp, pc/user.cpp, pc/user.hpp, pcapps/pyth.cpp
Closes #12 
Also, add dump_json() methods to pc::price and pc::product so we can have
standardized json output across all tools.
=> [pythd] Add get_product and get_all_products WS methods.

pc/manager.cpp, pc/manager.hpp, pc/request.cpp, pc/request.hpp, pc/rpc_client.cpp, pc/rpc_client.hpp
this is a partial change - the code to activate the polling is not included yet (but was tested locally)
this refactor should not change existing behavior, but allows for code deduplication
=> poll program accounts

CMakeLists.txt, program/src/oracle/sort.c, program/src/oracle/sort.h, program/src/oracle/test_oracle.c, program/src/oracle/upd_aggregate.h, pyth/tests/qset/11.result, pyth/tests/qset/2.result, pyth/tests/qset/31.result, pyth/tests/qset/33.result, pyth/tests/qset/35.result, pyth/tests/qset/36.result, pyth/tests/qset/37.result, pyth/tests/qset/39.result
=> filter out quoters far from median

CMakeLists.txt, pctest/test_twap.cpp, program/src/oracle/oracle.h, program/src/oracle/pd.h, program/src/oracle/upd_aggregate.h
separate some header files, update to c99 for local build (bpf is c17 - open issue to sync up)
=> build cleanup

pc/request.cpp, pc/request.hpp, pcapps/admin_request.cpp, pcapps/admin_request.hpp, pcapps/admin_rpc_client.cpp, pcapps/admin_rpc_client.hpp, pcapps/pyth.cpp, pcapps/pyth_admin.cpp, program/src/oracle/oracle.c, program/src/oracle/oracle.h, program/src/oracle/upd_aggregate.h
add support to enforce min number of publishers per price account to have a valid price (otherwise unknown)
=> set min publishers to have valid price

docker/Dockerfile, pyth/tests/conftest.py, pyth/tests/test_get_product.py
basic test
there are a number of improvements to this forthcoming:
- share the pythd connection to multiple tests
- move the asyncio to common func
- ref the product data from same place
- etc
just wanted to commit something that's working to start
=> test pythd

pyth/tests/conftest.py, pyth/tests/test_get_product.py
need for the batch update tests
=> test multiple products

README.md
Ensures that new publishers will use the latest version.
`test_publish.cpp` will be updated to use the new batching API in a subsequent PR.
=> Bump version in README Docker commands to use latest

program/rust/build.rs, program/rust/src/deserialize.rs, program/rust/src/error.rs, program/rust/src/lib.rs, program/rust/src/log.rs, program/rust/src/price_t_offsets.h
Adding extra logs for the logs based vs account based comparison.
=> Log time and ema

program/c/src/oracle/oracle.c, program/rust/src/c_oracle_header.rs, program/rust/src/processor.rs, program/rust/src/rust_oracle.rs, program/rust/src/tests/mod.rs, program/rust/src/tests/test_set_min_pub.rs
I had 20 mins so knocked out this easy instruction. Added a new test again because we didn't have one in the C.
=> Set min pub instruction

doc/example-nginx-blockdaemon.conf
Updating the example blockdaemon nginx config to use separate pythnet servers.
=> Update example blockdaemon nginx pythnet config

SECURITY.md
Updating the SECURITY.md with the bug bounty program and other details
=> updating security.md

program/rust/src/accounts/permission.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_permission_migration.rs, program/rust/src/tests/test_upd_price_no_fail_on_error.rs
Enable master authority to do all tasks.
=> Enable governance by master authority

program/c/src/oracle/model/price_model.h, program/c/src/oracle/sort/tmpl/sort_stable.c, program/c/src/oracle/util/avg.h, program/c/src/oracle/util/prng.h, program/rust/src/lib.rs
Certik typos + description of C+Rust setup.
=> Solve some typos

pcapps/pythd.cpp
added to the cases below but forgot it here. I validated that these work by printing to cout.
=> Fix option parsing bug

program/rust/Cargo.toml
We haven't updated this in a while and it was causing some confusion
=> Bump version of oracle

.github/workflows/docker.yaml, program/rust/Cargo.toml
I want to make a new release post authority migration
=> Bump cargo toml for 2.21.0

docker/Dockerfile, program/rust/Cargo.toml, program/rust/src/accounts.rs, program/rust/src/accounts/price.rs, program/rust/src/processor/upd_price.rs, program/rust/src/tests/test_message.rs, scripts/build-bpf.sh, scripts/check-size.sh
Add conditional compilation with the feature flag pythnet. We now check size for both pythnet and mainnet.
=> Conditional compilation

program/rust/src/accounts/price.rs, program/rust/src/processor/upd_price.rs
=> Decouple resizing and sending messages

Cargo.lock, program/rust/Cargo.toml
=> program/rust: bump version for release

SECURITY.md
This change updates the bounty terms
=> Update bounty terms
